React Calculator v-1: Milestone 2
mke2111/react-calculator pull request #2
Opened 2021-03-22 20:53 UTC by mke2111

## Milestone-2 ⚪ 

### In this milestone, I implemented the following features to the calculator:

- Add a components folder with 4 files to be used each with a given react component.
- 3 files within the components directory are rendered to the App component, which in turn is rendered in the index file.
- ES6 features are widely applied.

2021-03-22 23:55 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @mke2111! 👋 
 You have done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-22 23:55 UTC, BrittanyBlake commented on src/Components/Result.js
> +};
- [ ] the default value of the result prop should be set as 0
Screenshot from pathwright 👇🏾 
<img width="525" alt="Screen Shot 2021-03-23 at 12 45 46 AM" src="https://user-images.githubusercontent.com/48804258/112071945-1c761c80-8b71-11eb-97df-65cd92f83efc.png">

2021-03-22 23:55 UTC, BrittanyBlake commented on src/Components/DialPad.js
>          <button type="button">+/-</button>
- [ ] The ButtonPanel (`DialPad`) component should render the calculator panel using the Button (`SingleButton`) component, not the html `<button/>` tag.
Screenshot of requirements 👇🏾 
<img width="404" alt="Screen Shot 2021-03-23 at 12 52 48 AM" src="https://user-images.githubusercontent.com/48804258/112072434-1a608d80-8b72-11eb-9838-924afd3e9860.png">

2021-03-23 01:36 UTC, bellom approved these changes
## Hi @mke2111  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-03-23 12:02 UTC, merged